ALTER TABLE GRUPO DROP FOREIGN KEY FK_GRUPO_ID_CARRERA
ALTER TABLE AMISTAD DROP FOREIGN KEY FK_AMISTAD_AMIGO_ID
ALTER TABLE AMISTAD DROP FOREIGN KEY FK_AMISTAD_USUARIO_ID
DROP TABLE CARRERA
DROP TABLE GRUPO
DROP TABLE USUARIO
DROP TABLE AMISTAD
